version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - ../../.:/app
      - ./unit-conf.json:/unit-conf.json
      - ./unit.sh:/unit.sh
      - ./supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    working_dir: /app
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - redis
    networks:
      - omg-network


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      omg-network:
        aliases:
          - redis

networks:
  omg-network:
    driver: bridge
